using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Security.Cryptography;

namespace DO
{
    public class PasswordHandler
    {
        private static Random saltGenerator = new Random(); //generates the salt
        private static string hash(string passwordWithSalt) //hashes the password given
        {
            SHA512 shaM = new SHA512Managed();
            return Convert.ToBase64String(shaM.ComputeHash(Encoding.UTF8.GetBytes(passwordWithSalt)));
        }
        public static int generateSalt() //returns salt
        {
            return saltGenerator.Next();
        }
        public static string generateNewPassword(string password, int salt) //returns new password - hashed password generated by password and salt
        {
            return hash(password + salt);
        }
        public static bool checkPassword(string password, string hashed, int salt) //checks if the hashed password is the same as the password itselt after hash function
        {
            return hashed == hash(password + salt);
        }
    }
}
